---
# include file for debian distros
- include: raspbian-installation.yml

# set to auto-start the docker service when the system loads (distro independent)
- name: Set docker to start automatically
  systemd: enabled=yes name=docker
  when: ansible_service_mgr == "systemd"

# let normal user use docker without 'sudo' privilege escalation
- name: Create the docker group if it's not yet created
  group: 
    name: docker
    state: present

# change the user_id to the desired or create a variable
- name: Add user to group
  user:
    name: pi
    group: docker
    state: present