---
# Author: Jorge Hevia - jmhev@outlook.com
# This playbook installs docker-ce in debian following the official installation 
# found at https://docs.docker.com/install/linux/docker-ce/debian/

- name: Removes old versions of docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Installs required packages to add the docker-ce repository
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Adds docker-ce gpg key and enables repository
  shell: debian-add-repo.sh

- name: Installs docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes