---
#
# Author: Jorge Hevia
# What does this role do: this role installs Docker Community Edition (CE) on ubuntu 16 (for now), 
#                         it's done with repositories (cross fingers to work with proxies) 
# Working Ansible version: 2.3.0.0

- hosts: raspberrypi
  become: true
  roles:
      - role: docker_install 